name: Run Python

# Thanks to [https://github.com/JHUISI/charm/blob/dev/.github/workflows/ci.yml](https://github.com/JHUISI/charm/blob/dev/.github/workflows/ci.yml). 

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/Scheme*.py'
      - '**/requirements.txt'
      - '.github/workflows/runPython.yml'
      - 'analyze.py'
      - 'buildSchemeLaTeXPDFs.py'
  push:
    branches:
      - main
    paths:
      - '**/Scheme*.py'
      - '**/requirements.txt'
      - '.github/workflows/runPython.yml'
      - 'analyze.py'
      - 'buildSchemeLaTeXPDFs.py'
  workflow_dispatch:
    inputs:
      executeSchemeAAIBME:
        description: 'SchemeAAIBME'
        required: true
        default: true
        type: boolean
      executeSchemeCANIFPPCT:
        description: 'SchemeCANIFPPCT'
        required: true
        default: true
        type: boolean
      executeSchemeCoefficientComputation:
        description: 'SchemeCoefficientComputation'
        required: true
        default: true
        type: boolean
      executeSchemeFSMUAEKS:
        description: 'SchemeFSMUAEKS'
        required: true
        default: true
        type: boolean
      executeSchemeHIBME:
        description: 'SchemeHIBME'
        required: true
        default: true
        type: boolean
      executeSchemeIBMEMR:
        description: 'SchemeIBMEMR'
        required: true
        default: true
        type: boolean
      executeSchemeIBMETR:
        description: 'SchemeIBMETR'
        required: true
        default: true
        type: boolean
      executeSchemeIBPRME:
        description: 'SchemeIBPRME'
        required: true
        default: true
        type: boolean
      executeSchemeLBPEAKS:
        description: 'SchemeLBPEAKS'
        required: true
        default: true
        type: boolean
      executeSchemeFSLLRS:
        description: 'SchemeFSLLRS'
        required: true
        default: true
        type: boolean
      executeSchemeLWEPEKS:
        description: 'SchemeLWEPEKS'
        required: true
        default: true
        type: boolean
      executeSchemeVLPSICA:
        description: 'SchemeVLPSICA'
        required: true
        default: false
        type: boolean
      pythonVersion:
        description: 'Python version'
        required: true
        default: '3.x'
        type: choice
        options:
          - '3.x'
          - '3.12'
          - '3.13'
          - '3.14'
          - '3.15'
      outputFormat:
        description: 'Output format'
        required: true
        default: '.xlsx'
        type: choice
        options:
          - '.csv'
          - '.htm'
          - '.html'
          - '.json'
          - '.tex'
          - '.tsv'
          - '.txt'
          - '.xls'
          - '.xlsx'
          - '.xml'
          - '.yaml'
          - '.yml'
      decimalPlace:
        description: 'Decimal Place'
        required: true
        default: 9
        type: choice
        options:
          - 0
          - 's'
          - 'second'
          - 3
          - 'ms'
          - 'millisecond'
          - 6
          - 'microsecond'
          - 9
          - 'ns'
          - 'nanosecond'
          - 12
          - 'ps'
          - 'picosecond'
          - 15
          - 'fs'
          - 'femtosecond'
      runCount:
        description: 'Run count'
        required: true
        default: '10'
        type: string

permissions:
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
      decimalPlace: ${{ steps.decimalPlace.outputs.decimalPlace }}
      runCount: ${{ steps.runCount.outputs.runCount }}
      timeString: ${{ steps.timeString.outputs.timeString }}
    steps:
      - name: Prepare the matrix
        id: matrix
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]];
          then
            executeSchemeAAIBME="${{ github.event.inputs.executeSchemeAAIBME }}"
            executeSchemeCANIFPPCT="${{ github.event.inputs.executeSchemeCANIFPPCT }}"
            executeSchemeCoefficientComputation="${{ github.event.inputs.executeSchemeCoefficientComputation }}"
            executeSchemeFSMUAEKS="${{ github.event.inputs.executeSchemeFSMUAEKS }}"
            executeSchemeHIBME="${{ github.event.inputs.executeSchemeHIBME }}"
            executeSchemeIBMEMR="${{ github.event.inputs.executeSchemeIBMEMR }}"
            executeSchemeIBMETR="${{ github.event.inputs.executeSchemeIBMETR }}"
            executeSchemeIBPRME="${{ github.event.inputs.executeSchemeIBPRME }}"
            executeSchemeLBPEAKS="${{ github.event.inputs.executeSchemeLBPEAKS }}"
            executeSchemeFSLLRS="${{ github.event.inputs.executeSchemeFSLLRS }}"
            executeSchemeLWEPEKS="${{ github.event.inputs.executeSchemeLWEPEKS }}"
            executeSchemeVLPSICA="${{ github.event.inputs.executeSchemeVLPSICA }}"
          else
            executeSchemeAAIBME="true"
            executeSchemeCANIFPPCT="true"
            executeSchemeCoefficientComputation="true"
            executeSchemeFSMUAEKS="true"
            executeSchemeHIBME="true"
            executeSchemeIBMEMR="true"
            executeSchemeIBMETR="true"
            executeSchemeIBPRME="true"
            executeSchemeLBPEAKS="true"
            executeSchemeFSLLRS="true"
            executeSchemeLWEPEKS="true"
            executeSchemeVLPSICA="false"
          fi
          matrix=()
          [[ "true" == "${executeSchemeAAIBME}" ]] && matrix+=("SchemeAAIBME/SchemeAAIBME.py" "SchemeAAIBME/SchemeFuzzyME.py" "SchemeIBMETR/SchemeIBMECH.py")
          [[ "true" == "${executeSchemeCANIFPPCT}" ]] && matrix+=("SchemeCANIFPPCT/SchemeCANIFPPCT.py" "SchemeCANIFPPCT/SchemeCANIPSI.py")
          [[ "true" == "${executeSchemeCoefficientComputation}" ]] && matrix+=("SchemeCoefficientComputation/SchemeCoefficientComputation.py")
          [[ "true" == "${executeSchemeFSMUAEKS}" ]] && matrix+=("SchemeFSMUAEKS/SchemeFSMUAEKS.py")
          [[ "true" == "${executeSchemeHIBME}" ]] && matrix+=("SchemeHIBME/SchemeAnonymousME.py" "SchemeHIBME/SchemeHIBME.py")
          [[ "true" == "${executeSchemeIBMEMR}" ]] && matrix+=("SchemeIBMEMR/SchemeIBBME.py" "SchemeIBMETR/SchemeIBME.py" "SchemeIBMEMR/SchemeIBMEMR.py")
          [[ "true" == "${executeSchemeIBMETR}" ]] && matrix+=("SchemeIBMETR/SchemeAIBE.py" "SchemeIBMETR/SchemeARES.py" "SchemeIBMETR/SchemeIBME.py" "SchemeIBMETR/SchemeIBMECH.py" "SchemeIBMETR/SchemeIBMETR.py")
          [[ "true" == "${executeSchemeIBPRME}" ]] && matrix+=("SchemeIBMETR/SchemeIBME.py" "SchemeIBMETR/SchemeIBMECH.py" "SchemeIBPRME/SchemeIBPME.py" "SchemeIBPRME/SchemeIBPRME.py" "SchemeIBPRME/SchemePBAC.py")
          [[ "true" == "${executeSchemeLBPEAKS}" ]] && matrix+=("SchemeLBPEAKS/SchemeLBPEAKS.py")
          [[ "true" == "${executeSchemeFSLLRS}" ]] && matrix+=("SchemeFSLLRS/SchemeFSLLRS.py")
          [[ "true" == "${executeSchemeLWEPEKS}" ]] && matrix+=("SchemeLWEPEKS/SchemeLWEPEKS.py")
          [[ "true" == "${executeSchemeVLPSICA}" ]] && matrix+=("SchemeVLPSICA/SchemeVLPSICA.py")
          if [[ ${#matrix[@]} -ge 1 ]];
          then
            echo "matrix=$(printf '%s\n' "${matrix[@]}" | jq -R . | jq -s -c 'unique')" >> "${GITHUB_OUTPUT}"
          else
            echo "matrix=[]" >> "${GITHUB_OUTPUT}"
          fi
      
      - name: Prepare the decimal place
        id: decimalPlace
        run: |
          cd "${{ github.workspace }}"
          case "${decimalPlaceString}" in
            0|s|second)
              decimalPlace=0
              ;;
            3|ms|millisecond)
              decimalPlace=3
              ;;
            6|microsecond)
              decimalPlace=6
              ;;
            9|ns|nanosecond)
              decimalPlace=9
              ;;
            12|ps|picosecond)
              decimalPlace=12
              ;;
            15|fs|femtosecond)
              decimalPlace=15
              ;;
            *)
              decimalPlace=9
              ;;
          esac
          echo "decimalPlace=${decimalPlace}" >> "${GITHUB_OUTPUT}"
        env:
          decimalPlaceString: ${{ github.event.inputs.decimalPlace || '9' }}
      
      - name: Prepare the run count
        id: runCount
        run: |
          cd "${{ github.workspace }}"
          integerNumberString="$(echo -n "${runCountString}" | tr -cd '0-9A-Za-z+.-' | tr 'A-Z' 'a-z')"
          leadingSigns="${integerNumberString%%[!+-]*}"
          minusCount=$(echo -n "${leadingSigns}" | tr -cd '-' | wc -c)
          integerNumberString="${integerNumberString#$leadingSigns}"
          integerNumberString="$(echo "${integerNumberString}" | sed 's/^0*//')"
          radix=0
          case "${integerNumberString:0:1}" in
            'b')
              radix=2
              integerNumberString="${integerNumberString:1}"
              ;;
            'q')
              radix=4
              integerNumberString="${integerNumberString:1}"
              ;;
            'o')
              radix=8
              integerNumberString="${integerNumberString:1}"
              ;;
            'd')
              radix=10
              integerNumberString="${integerNumberString:1}"
              ;;
            'x')
              radix=16
              integerNumberString="${integerNumberString:1}"
              ;;
          esac
          if [[ 0 -eq ${radix} ]];
          then
            case "${integerNumberString: -1}" in
              'b')
                radix=2
                integerNumberString="${integerNumberString:0:-1}"
                ;;
              'q')
                radix=4
                integerNumberString="${integerNumberString:0:-1}"
                ;;
              'o')
                radix=8
                integerNumberString="${integerNumberString:0:-1}"
                ;;
              'd')
                radix=10
                integerNumberString="${integerNumberString:0:-1}"
                ;;
              'x')
                radix=16
                integerNumberString="${integerNumberString:0:-1}"
                ;;
              *)
                radix=10
                ;;
            esac
          fi
          integerNumberString="$(echo "${integerNumberString}" | sed 's/^0*//')"
          integerNumberString="${integerNumberString%%.*}"
          runCount=0
          { runCount=$((${radix}#$integerNumberString)); } 2>/dev/null
          if (( minusCount % 2 == 1 ));
          then
            runCount=$(( -runCount ))
          fi
          if [[ ${runCount} -lt 1 ]];
          then
            runCount=10
          fi
          echo "runCount=${runCount}" >> "${GITHUB_OUTPUT}"
        env:
          runCountString: ${{ github.event.inputs.runCount || '10' }}
      
      - name: Prepare the time string
        id: timeString
        run: |
          cd "${{ github.workspace }}"
          timeString="HKT$(date '+%Y%m%d%H%M%S')"
          echo "timeString=${timeString}" >> "${GITHUB_OUTPUT}"
        env:
          TZ: 'Asia/Hong_Kong'
  
  runPython:
    if: ${{ needs.prepare.outputs.matrix != '[]' }}
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cryptographicScheme: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          sparse-checkout: |
            **/Scheme*.py
            **/requirements.txt
            analyze.py
            buildSchemeLaTeXPDFs.py
          sparse-checkout-cone-mode: false
          persist-credentials: false
      
      - name: Get ready
        id: ready
        run: |
          cd "${{ github.workspace }}"
          directoryPath="$(dirname -- "${{ matrix.cryptographicScheme }}")"
          requirementFilePath="${directoryPath}/requirements.txt"
          if [[ -f "${requirementFilePath}" ]] && grep -qiF "charm" "${requirementFilePath}";
          then
            charmBasedScheme="true"
          else
            charmBasedScheme="false"
          fi
          mainFileName="$(basename -- "${{ matrix.cryptographicScheme }}" | sed "s/\.[^.]*\$//g")"
          outputFilePath="${directoryPath}/${mainFileName}-Python${pythonVersion}-p${decimalPlace}-r${runCount}-${timeString}${outputFormat}"
          outputFileName="$(basename "${outputFilePath}")"
          schemeLaTeXFilePath="${directoryPath}/${mainFileName}LaTeX/${mainFileName}-${timeString}.tex"
          schemePDFFilePath="${directoryPath}/${mainFileName}LaTeX/${mainFileName}-${timeString}.pdf"
          analysisFilePath="${directoryPath}/${mainFileName}Figures.zip"
          echo "Cryptographic scheme: ${{ matrix.cryptographicScheme }}"
          echo "Requirement file path: ${requirementFilePath}"
          echo "Charm-based scheme: ${charmBasedScheme}"
          echo "Python version: ${pythonVersion}"
          echo "Decimal place: ${decimalPlaceString} (${decimalPlace})"
          echo "Run count: ${runCount}"
          echo "Time string: ${timeString}"
          echo "Output format: ${outputFormat}"
          echo "Output file path: ${outputFilePath}"
          echo "Output file name: ${outputFileName}"
          echo "Scheme LaTeX file path: ${schemeLaTeXFilePath}"
          echo "Scheme PDF file path: ${schemePDFFilePath}"
          echo "Analysis file path: ${analysisFilePath}"
          echo "requirementFilePath=${requirementFilePath}" >> "${GITHUB_OUTPUT}"
          echo "charmBasedScheme=${charmBasedScheme}" >> "${GITHUB_OUTPUT}"
          echo "outputFilePath=${outputFilePath}" >> "${GITHUB_OUTPUT}"
          echo "outputFileName=${outputFileName}" >> "${GITHUB_OUTPUT}"
          echo "schemeLaTeXFilePath=${schemeLaTeXFilePath}" >> "${GITHUB_OUTPUT}"
          echo "schemePDFFilePath=${schemePDFFilePath}" >> "${GITHUB_OUTPUT}"
          echo "analysisFilePath=${analysisFilePath}" >> "${GITHUB_OUTPUT}"
        env:
          pythonVersion: ${{ github.event.inputs.pythonVersion || '3.x' }}
          decimalPlaceString: ${{ github.event.inputs.decimalPlace || '9' }}
          decimalPlace: ${{ needs.prepare.outputs.decimalPlace }}
          runCount: ${{ needs.prepare.outputs.runCount }}
          timeString: ${{ needs.prepare.outputs.timeString }}
          outputFormat: ${{ github.event.inputs.outputFormat || '.xlsx' }}
      
      - name: Install system dependencies
        run: |
          cd "${{ github.workspace }}"
          sudo apt-get update
          sudo apt-get install -y flex libfl-dev libgmp-dev libssl-dev texlive-latex-base wget
      
      - name: Set up Python ${{ github.event.inputs.pythonVersion || '3.x' }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ github.event.inputs.pythonVersion || '3.x' }}
      
      - name: Install Python dependencies
        run: |
          cd "${{ github.workspace }}"
          python -m pip install --upgrade pip
          python -m pip install wheel
          python -m pip install -r requirements.txt -r "${{ steps.ready.outputs.requirementFilePath }}"
      
      - name: Build LaTeX and the PDF for the cryptographic scheme
        run: |
          cd "${{ github.workspace }}"
          echo "The current working directory is \"$(pwd)\". "
          if [[ -f buildSchemeLaTeXPDFs.py && -f "${{ matrix.cryptographicScheme }}" ]];
          then
            formatString='%p/%nLaTeX/%n-${{ needs.prepare.outputs.timeString }}'
            echo "\$ python buildSchemeLaTeXPDFs.py -t 0 -h"
            python buildSchemeLaTeXPDFs.py -t 0 -h
            echo "\$ python buildSchemeLaTeXPDFs.py -o \"${formatString}\" -t 0 -- \"${{ matrix.cryptographicScheme }}\""
            python buildSchemeLaTeXPDFs.py -o "${formatString}" -t 0 -- "${{ matrix.cryptographicScheme }}"
          else
            echo "Could not execute the LaTeX and PDF builder \"buildSchemeLaTeXPDFs.py\" via Python ${{ github.event.inputs.pythonVersion || '3.x' }}. "
            tree
          fi
      
      - name: Upload the LaTeX source code for the cryptographic scheme
        uses: actions/upload-artifact@v7
        with:
          path: ${{ github.workspace }}/${{ steps.ready.outputs.schemeLaTeXFilePath }}
          archive: false
          if-no-files-found: warn
      
      - name: Upload the PDF for the cryptographic scheme
        uses: actions/upload-artifact@v7
        with:
          path: ${{ github.workspace }}/${{ steps.ready.outputs.schemePDFFilePath }}
          archive: false
          if-no-files-found: warn
      
      - name: Build and install the PBC library
        if: ${{ steps.ready.outputs.charmBasedScheme == 'true' }}
        run: |
          cd "${{ github.workspace }}"
          wget https://crypto.stanford.edu/pbc/files/pbc-1.0.0.tar.gz
          tar -xzf pbc-1.0.0.tar.gz
          cd pbc-1.0.0
          ./configure LDFLAGS="-lgmp"
          make -j$(nproc)
          sudo make install
          sudo ldconfig
      
      - name: Build and install the Python Charm-Crypto framework
        if: ${{ steps.ready.outputs.charmBasedScheme == 'true' }}
        run: |
          cd "${{ github.workspace }}"
          git clone https://github.com/JHUISI/charm
          cd charm
          chmod +x ./configure.sh
          ./configure.sh
          make -j$(nproc)
          sudo make install
      
      - name: Run the cryptographic scheme
        run: |
          cd "${{ github.workspace }}"
          echo "The current working directory is \"$(pwd)\". "
          if [[ -f "${{ matrix.cryptographicScheme }}" ]];
          then
            echo "\$ python \"${{ matrix.cryptographicScheme }}\" -t 0 -h"
            python "${{ matrix.cryptographicScheme }}" -t 0 -h
            echo ""
            echo "\$ python \"${{ matrix.cryptographicScheme }}\" -o \"${{ steps.ready.outputs.outputFileName }}\" -p ${{ needs.prepare.outputs.decimalPlace }} -r ${{ needs.prepare.outputs.runCount }} -t 0 -y"
            python "${{ matrix.cryptographicScheme }}" -o "${{ steps.ready.outputs.outputFileName }}" -p ${{ needs.prepare.outputs.decimalPlace }} -r ${{ needs.prepare.outputs.runCount }} -t 0 -y
          else
            echo "Could not execute the cryptographic scheme file \"${{ matrix.cryptographicScheme }}\" via Python ${{ github.event.inputs.pythonVersion || '3.x' }}. "
            tree
          fi
      
      - name: Upload the result
        uses: actions/upload-artifact@v7
        with:
          path: ${{ github.workspace }}/${{ steps.ready.outputs.outputFilePath }}
          archive: false
          if-no-files-found: error
      
      - name: Analyze
        run: |
          cd "${{ github.workspace }}"
          echo "The current working directory is \"$(pwd)\". "
          if [[ -f "analyze.py" ]];
          then
            echo "\$ python \"analyze.py\" -t 0 -h"
            python "analyze.py" -t 0 -h
            echo ""
            echo "\$ python \"analyze.py\" -t 0 -- \"${{ steps.ready.outputs.outputFileName }}\""
            python "analyze.py" -t 0 -- "${{ steps.ready.outputs.outputFileName }}"
          else
            echo "Could not execute the analyzer \"analyze.py\" via Python ${{ github.event.inputs.pythonVersion || '3.x' }}. "
            tree
          fi
      
      - name: Upload the analysis
        uses: actions/upload-artifact@v7
        with:
          path: ${{ github.workspace }}/${{ steps.ready.outputs.analysisFilePath }}
          archive: false
          if-no-files-found: warn